export const categories = [
  // Chi tiêu
  {
    id: "food",
    name: "Ăn uống",
    icon: "utensils",
    color: "bg-red-100",
    iconColor: "text-red-500",
    type: "expense",
  },
  {
    id: "housing",
    name: "Nhà ở",
    icon: "home",
    color: "bg-purple-100",
    iconColor: "text-purple-500",
    type: "expense",
  },
  {
    id: "transport",
    name: "Di chuyển",
    icon: "car",
    color: "bg-blue-100",
    iconColor: "text-blue-500",
    type: "expense",
  },
  {
    id: "entertainment",
    name: "Giải trí",
    icon: "gamepad",
    color: "bg-green-100",
    iconColor: "text-green-500",
    type: "expense",
  },
  {
    id: "shopping",
    name: "Mua sắm",
    icon: "shopping-bag",
    color: "bg-orange-100",
    iconColor: "text-orange-500",
    type: "expense",
  },
  {
    id: "health",
    name: "Y tế",
    icon: "heartbeat",
    color: "bg-pink-100",
    iconColor: "text-pink-500",
    type: "expense",
  },
  {
    id: "education",
    name: "Giáo dục",
    icon: "graduation-cap",
    color: "bg-indigo-100",
    iconColor: "text-indigo-500",
    type: "expense",
  },
  {
    id: "utilities",
    name: "Điện nước",
    icon: "bolt",
    color: "bg-yellow-100",
    iconColor: "text-yellow-500",
    type: "expense",
  },

  // Thu nhập
  {
    id: "salary",
    name: "Lương",
    icon: "money-bill",
    color: "bg-green-100",
    iconColor: "text-green-500",
    type: "income",
  },
  {
    id: "bonus",
    name: "Thưởng",
    icon: "gift",
    color: "bg-yellow-100",
    iconColor: "text-yellow-500",
    type: "income",
  },
  {
    id: "investment",
    name: "Đầu tư",
    icon: "chart-line",
    color: "bg-blue-100",
    iconColor: "text-blue-500",
    type: "income",
  },
  {
    id: "gift",
    name: "Quà tặng",
    icon: "birthday-cake",
    color: "bg-pink-100",
    iconColor: "text-pink-500",
    type: "income",
  },
  {
    id: "other-income",
    name: "Khác (Thu)",
    icon: "ellipsis-h",
    color: "bg-gray-100",
    iconColor: "text-gray-500",
    type: "income",
  },
];

export const mockTransactions = [
  {
    id: 1,
    title: "Nhà hàng Phương Nam",
    amount: -350000,
    category: "food",
    date: "19/06/2025",
    type: "expense",
  },
  {
    id: 2,
    title: "Siêu thị Vinmart",
    amount: -420000,
    category: "shopping",
    date: "18/06/2025",
    type: "expense",
  },
  {
    id: 3,
    title: "Lương tháng 6",
    amount: 12000000,
    category: "salary",
    date: "15/06/2025",
    type: "income",
  },
  {
    id: 4,
    title: "Tiền thuê nhà",
    amount: -3000000,
    category: "housing",
    date: "10/06/2025",
    type: "expense",
  },
];

export const navigationItems = [
  { key: 'home', label: 'navigation.home', icon: 'home' },
  { key: 'transactions', label: 'navigation.transactions', icon: 'exchange-alt' },
  { key: 'statistics', label: 'navigation.statistics', icon: 'chart-pie' },
  { key: 'budgets', label: 'navigation.budgets',   icon: 'piggy-bank' },
  { key: 'settings', label: 'navigation.settings', icon: 'cog' },
];

export const bottomNavItems = [
  { key: 'home', label: 'navigation.home', icon: 'home' },
  { key: 'transactions', label: 'navigation.transactions', icon: 'exchange-alt' },
  { key: 'add', label: 'navigation.add', icon: 'plus' },
  { key: 'statistics', label: 'navigation.statistics', icon: 'chart-pie' },
  { key: 'settings', label: 'navigation.settings', icon: 'cog' },
]; 
